services:
  - type: web
    name: cyber-threat-detector-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: |
      gunicorn src.app.api:app \
        --workers 1 \
        --worker-class uvicorn.workers.UvicornWorker \
        --bind 0.0.0.0:$PORT \
        --timeout 120 \
        --log-level debug \
        --access-logfile - \
        --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: DEBUG
    healthCheckPath: /health
    autoDeploy: true